### ISSUE TITLE
Dalao could you provide more details about requirement and environment?

### ISSUE THREAD

**Issue by sethGu** [SongW-SW/FAITH#1]
Dear dalao,

I'm using pytorch 1.8.1 with CUDA 11.3.1, but when I running train.py it said "AssertionError: Torch not compiled with CUDA enabled".
When I check "torch.cuda.is_available()" it return a False.
Could you please provide more details about requirement and environment?

感激不尽~~

**Comment by SongW-SW** [comment]
Hi I would consider it an environment problem. You may check whether the torch with gpu is correctly installed.

**Comment by sethGu** [comment]
Hi there, I'm sure my GPU is ready for work at other graph learning tasks. I tried different versions of cudatoolkit (10.2, 11.3, 11.6) with pytorch 1.8.1 but still doesn't work. 
It confuses me because I cannot find any solutions with google. And more important is, it is the first time I met this problem throughout my career of pytorch usage. Thus I would like to hear from the detailed environment of your excellent work.

![image](https://user-images.githubusercontent.com/45868017/200163260-57a6b318-ffa9-4e7a-9215-205ae2f2d7a3.png)

**Comment by SongW-SW** [comment]
Hi, I'm using '1.11.0+cu113' and it can work. Maybe you can try different torch versions.
